### ISSUE TITLE
The snap needs svg support library

### ISSUE THREAD

**Issue by Rescator7** [GeorgScheumann/Hearts-snap#2]
1) Switching deck to English or Russian create empty images.

While the standard deck is in PGN, the English and Russian are SVG format.

2) The online buttons: "Exit, Leave, Create table" are invisible. The paomedia icons used are in SVG format. 
The other buttons are PGN.

So, SVG library support is missing in the package. I Guess. "Qt SVG" ?

https://github.com/Rescator7/Hearts/blob/master/screenshot/SCR2-hearts-1.6.jpg

Thanks,
Taking times creating this snap of my card Game!

Rescator

**Comment by GSchuemann** [comment]
You are right, never changed the deck. As for multiplayer, I only tested the server connection and nothing more, since I had no people to play online with them. Will look into adding the qt svg package as a dependency.

**Comment by GSchuemann** [comment]
The snap has been built on the server and is available now. To upgrade right away, type 
`snap refresh hearts`
. 

> Thanks,
Taking times creating this snap of my card Game!

Well your version of hearts actually was the easiest to snap. You could also do this upstream, if you want to, I can transfer this snap to you.

**Comment by Rescator7** [comment]
No needs to transfer the snap. I'm happy someone else created a package for the game. Maybe, it's not that hard, but that way i can focus more on the game. Beside, it's an hobby that i'm working on here and there, and sometimes after a long break.

There is a build for OpenSuse made by AndNovember at:

https://build.opensuse.org/package/show/home:AndnoVember:LXQT/hearts

But, is outdated to version 1.4b.

Your snap package is up to date and compatible with all distros. it's a PLUS.

Thanks.
Rescator.


________________________________

**Comment by GSchuemann** [comment]
Okay, feel free to notify me, if I miss a release of your game.
